# Generated by Django 4.1.1 on 2022-09-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_alter_todo_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="description",
            field=models.CharField(default="default", max_length=1000),
            preserve_default=False,
        ),
    ]
